### ISSUE TITLE
What reason to delete branch 2.2?

### ISSUE THREAD

**Issue by fiftin** [fdintino/nginx-upload-module#107]
I used branch 2.2 because it only working correctly. What reason to delete it? Where I can get source code from branch 2.2?

**Comment by fdintino** [comment]
It was deleted because the 2.2 branch became the master branch, so there wasn't any difference except that the 2.2 branch was out of date so it was missing bug fixes. The master branch and the 2.3.0 tag should work for you. The commit sha for the 2.2 branch was e299d8e9743991b17436ca67c18c82bb4449684c but I suggest you try the latest version, which should also work correctly.

**Comment by fiftin** [comment]
Thank you very match!
