### ISSUE TITLE
Versioned Release

### ISSUE THREAD

**Issue by TBoshoven** [fdintino/nginx-upload-module#99]
The latest release of this module (2.2.0) is over 7 years old.
It does not work as expected with the current version of nginx.
Since the master branch seems to work, it's probably time for a new release.
It would be beneficial to have a new version number so that requirements work out as expected.

**Comment by khavishbhundoo** [comment]
There is still some work to be done for a proper release in my opinion.I have created an issue about it @ #101

**Comment by fdintino** [comment]
I've changed my mind a bit on this. I think there are enough fixes to make having a 2.3.0 release worthwhile, and to not hold it up before the other issues are sorted. Not having a release after 2.2.0 was confusing people, since that release no longer builds against recent versions of nginx. I'll close this issue but keep open #101 to track progress towards a next-release roadmap.
